[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/create-game"
  to = "/.netlify/functions/create-game"
  status = 200

[[redirects]]
  from = "/get-word"
  to = "/.netlify/functions/get-word"
  status = 200